Update to Secp Keys
LegReq/artifacts pull request #4
Opened 2022-03-21 21:49 UTC by wip-abramson

2022-03-22 23:39 UTC, wip-abramson commented
Okay, @jandrieu I believe this is the reorg that we discussed. Let me know if anything looks off.

2022-03-23 02:22 UTC, jandrieu requested changes
Unfortunately, did doc is an unfortunate and outdated term.

I'd like to switch all of these to just "did". So the folder is "dids" and each file has "did" in it instead of "diddoc", e.g., `certifier.did.json`

2022-03-23 17:55 UTC, wip-abramson commented
Okay @jandrieu this should be good to go now. I also updated the Readme to reflect the new artifacts and file structure.

In the future I will look to add tutorial for how to generate own artifacts using didkit.

2022-03-25 04:08 UTC, jandrieu requested changes
add "document" to did document references

2022-03-25 04:08 UTC, jandrieu commented on README.md
> +  * DID [./rec/dids/hydroelec.did.json](./rec/dids/hydroelec.did.json)
```suggestion
  * DID document [./rec/dids/hydroelec.did.json](./rec/dids/hydroelec.did.json)
```

2022-03-25 04:08 UTC, jandrieu commented on README.md
> +  * DID [./rec/dids/meter1.did.json](./rec/dids/meter1.did.json)
```suggestion
  * DID document [./rec/dids/meter1.did.json](./rec/dids/meter1.did.json)
```

2022-03-25 04:08 UTC, jandrieu commented on README.md
> +  * DID [./rec/dids/meter2.did.json](./rec/dids/meter2.did.json)
```suggestion
  * DID document [./rec/dids/meter2.did.json](./rec/dids/meter2.did.json)
```

2022-03-25 04:08 UTC, jandrieu commented on README.md
> +  * DID [./rec/dids/unfccc.did.json](./rec/dids/unfccc.did.json)
```suggestion
  * DID document [./rec/dids/unfccc.did.json](./rec/dids/unfccc.did.json)
```

2022-03-25 04:08 UTC, jandrieu commented on README.md
> +  * DID [./rec/dids/certifier.did.json](./rec/dids/certifier.did.json)
```suggestion
  * DID document [./rec/dids/certifier.did.json](./rec/dids/certifier.did.json)
```

2022-03-25 04:08 UTC, jandrieu commented on README.md
> +  * DID [./rec/dids/verifier.did.json](./rec/dids/verifier.did.json)
```suggestion
  * DID document [./rec/dids/verifier.did.json](./rec/dids/verifier.did.json)
```

2022-03-25 04:08 UTC, jandrieu commented on README.md
> +When this DID is resolved it returns the DID Document found in [./rec/dids/hydroelec.did.json](./rec/dids/hydroelec.did.json)
```suggestion
When this DID is resolved it returns the DID document found in [./rec/dids/hydroelec.did.json](./rec/dids/hydroelec.did.json)
```

2022-03-25 04:08 UTC, jandrieu commented on README.md
> +  * DID [./rec/dids/un.rec2022.did.json](./rec/dids/un.rec2022.did.json)
```suggestion
  * DID document [./rec/dids/un.rec2022.did.json](./rec/dids/un.rec2022.did.json)
```

2022-03-25 04:11 UTC, wip-abramson commented on README.md
> +The public/private key pairs are Secp256k1 keys generated using [didkit](https://spruceid.dev/docs/didkit/) and represented in [Json Web Key](https://datatracker.ietf.org/doc/html/rfc7517) format. Th
```suggestion
The public/private key pairs are Secp256k1 keys generated using [didkit](https://spruceid.dev/docs/didkit/) and represented in [Json Web Key](https://datatracker.ietf.org/doc/html/rfc7517) format. The .jwk files contain both the public and private keys for each actor. From these keys a DID and associated DID document has been generated using didkit.
```

2022-03-25 04:12 UTC, jandrieu approved these changes

2022-03-25 04:12 UTC, merged